services:
  nats:
    image: nats:2.11.4-alpine3.21
    volumes:
      - ./local/nats:/etc/nats
      - ./local/jwt:/jwt
    ports:
      - "4222:4222"
      - "8222:8222"
  nats-box:
    image: natsio/nats-box:0.18.0-nonroot
    init: true
    command: ["sleep", "infinity"]
    environment:
      NATS_URL: nats://nats:4222
      NATS_CREDS: /nsc/nkeys/creds/root/root/root.creds
    volumes:
      - ./local/nsc:/nsc
  proxy:
    image: nats-limiter-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UPSTREAM_HOST: nats
      UPSTREAM_PORT: 4222
    ports:
      - "4223:4223"
    volumes:
    - ./config.yaml:/app/config.yaml:ro