services:
  nats:
    image: nats:2.11.4-alpine3.21
    command: ["-c", "/nats-server.conf"]
    volumes:
      - ./local/nats-server.conf:/nats-server.conf
    ports:
      - "4222:4222"
      - "8222:8222"
    
  proxy:
    image: nats-limiter-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UPSTREAM_HOST: nats
      UPSTREAM_PORT: 4222
    ports:
      - "4223:4223"
