services:
  nats:
    image: nats:2.11.4-alpine3.21
    volumes:
      - ./local/nats:/etc/nats
      - nats-jwt:/jwt
      - nats-data:/data
    ports:
      - "4222:4222"
      - "8222:8222"
  nats-box:
    image: natsio/nats-box:0.18.0-nonroot
    init: true
    command: ["sleep", "infinity"]
    volumes:
      - ./local/nsc:/nsc
      - ./local/scripts:/scripts
  proxy:
    image: nats-limiter-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UPSTREAM_HOST: nats
      UPSTREAM_PORT: "4222"
      LOG_LEVEL: "debug"
      
    ports:
      - "4223:4223"
    volumes:
    - ./config.yaml:/app/config.yaml:ro
volumes:
  nats-jwt:
  nats-data:
